// Builds the GitHub Pages site for this repo into _site/ (gitignored).
//
// For every folder under projects/ that has a web/index.html, copies that
// web/ folder to _site/<project>/ and lists it on a generated
// _site/index.html. Each project's title and one-line summary come from
// its own README.md (the "# Title" heading and the first paragraph after
// it), so adding a project needs nothing done here — see CLAUDE.md.
//
// Links on the index are relative (./<project>/), so the site works both
// at the github.io/<repo>/ subpath and served locally from _site/.
//
//   node scripts/build-pages.mjs
//   python3 -m http.server -d _site 8000   # optional local preview

import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('../', import.meta.url));
const PROJECTS_DIR = ROOT + 'projects/';
const OUT_DIR = ROOT + '_site/';
const REPO_URL = 'https://github.com/bvandersen/playground';

function escapeHtml(value) {
	return value.replace(
		/[&<>"']/g,
		(char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]
	);
}

// "# Title" + the first plain paragraph after it, with light markdown stripped.
function readReadme(dir, name) {
	const path = dir + 'README.md';
	if (!existsSync(path)) return { title: name, summary: null };
	const lines = readFileSync(path, 'utf8').split('\n');
	const h1 = lines.findIndex((line) => /^#\s+/.test(line));
	const title = h1 >= 0 ? lines[h1].replace(/^#\s+/, '').trim() : name;
	const paragraph = [];
	for (const line of lines.slice(h1 + 1)) {
		if (!line.trim()) {
			if (paragraph.length) break;
			continue;
		}
		if (/^(#|>|```|[-*]\s|\|)/.test(line)) {
			if (paragraph.length) break;
			continue;
		}
		paragraph.push(line.trim());
	}
	const summary = paragraph.length
		? paragraph.join(' ').replace(/\[([^\]]+)\]\([^)]+\)/g, '$1').replace(/[*_`]/g, '')
		: null;
	return { title, summary };
}

function readProjects() {
	if (!existsSync(PROJECTS_DIR)) return [];
	return readdirSync(PROJECTS_DIR)
		.filter((name) => statSync(PROJECTS_DIR + name).isDirectory())
		.sort((a, b) => a.localeCompare(b))
		.flatMap((name) => {
			const dir = PROJECTS_DIR + name + '/';
			if (!existsSync(dir + 'web/index.html')) {
				console.log(`build-pages: skipping ${name} (no web/index.html)`);
				return [];
			}
			return [{ name, dir, ...readReadme(dir, name) }];
		});
}

function renderRow(project) {
	const summaryHtml = project.summary ? `\n        <p>${escapeHtml(project.summary)}</p>` : '';
	return `      <li>
        <a class="demo" href="./${encodeURIComponent(project.name)}/">${escapeHtml(project.title)}</a>${summaryHtml}
        <a class="src" href="${REPO_URL}/tree/main/projects/${encodeURIComponent(project.name)}">Source and notes</a>
      </li>`;
}

function renderPage(projects) {
	const rows = projects.length
		? projects.map(renderRow).join('\n')
		: '      <li><p>No demos yet.</p></li>';
	return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="robots" content="noindex, nofollow" />
<title>Playground demos</title>
<!-- Generated by scripts/build-pages.mjs — do not hand-edit. -->
<style>
  :root { color-scheme: dark; }
  html, body {
    margin: 0;
    background: #0e1420;
    color: #e2e8f0;
    font: 15px/1.5 system-ui, -apple-system, "Segoe UI", sans-serif;
  }
  main { max-width: 720px; margin: 0 auto; padding: 48px 16px 80px; }
  h1 { color: #f1f5f9; margin-bottom: 4px; }
  .lede { color: #93a3b8; margin-top: 0; }
  a { color: #93c5fd; }
  ul { list-style: none; padding: 0; margin: 32px 0 0; }
  li { padding: 16px 0; border-top: 1px solid #1e293b; }
  li p { margin: 6px 0; color: #94a3b8; font-size: 14px; }
  .demo { font-size: 17px; font-weight: 600; text-decoration: none; }
  .demo:hover { text-decoration: underline; }
  .src { font-size: 13px; color: #64748b; }
</style>
</head>
<body>
<main>
  <h1>Playground demos</h1>
  <p class="lede">Every project in <a href="${REPO_URL}">this repo</a>, listed automatically.</p>
  <ul>
${rows}
  </ul>
</main>
</body>
</html>
`;
}

const projects = readProjects();
rmSync(OUT_DIR, { recursive: true, force: true });
mkdirSync(OUT_DIR, { recursive: true });
for (const project of projects) cpSync(project.dir + 'web', OUT_DIR + project.name, { recursive: true });
writeFileSync(OUT_DIR + 'index.html', renderPage(projects));
writeFileSync(OUT_DIR + '.nojekyll', '');
console.log(`build-pages: wrote ${OUT_DIR} with ${projects.length} project(s): ${projects.map((p) => p.name).join(', ')}`);
