// Generates static/game2/index.html — a landing page that links to every
// Godot-exported demo under static/game2/ and to the plan that documents
// them (docs/game2.md). Same role as scripts/game-index.mjs plays for
// static/game/, adapted for the fact that a game2 demo is a *folder*
// (a Godot Web export: index.html, .wasm, .pck, .js) rather than a single
// standalone .html file.
//
// Generated, not hand-written, for the same reason: every demo's title
// comes straight from that demo's own exported <title>, scanned fresh
// each run, so adding, removing, or re-exporting a demo needs nothing
// else done for it to appear here correctly.
//
// Runs automatically before both `npm run dev` and `npm run build` (see
// the "predev"/"prebuild" scripts in package.json, alongside
// scripts/game-index.mjs's own entry) — this is safe to run on every
// build because it's a pure directory scan over already-committed static
// files, with zero Godot dependency (see docs/game2.md, "Why the Godot
// export is never part of `npm run build`"). The generated
// static/game2/index.html is gitignored, not committed, same reasoning
// as static/game/index.html.
//
//   node scripts/game2-index.mjs

import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const GAME2_DIR = fileURLToPath(new URL('../static/game2/', import.meta.url));
const OUTPUT_FILE = GAME2_DIR + 'index.html';
const DOC_URL = 'https://github.com/bvandersen/playground/blob/main/docs/game2.md';

function escapeHtml(value) {
	return value.replace(
		/[&<>"']/g,
		(char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]
	);
}

function extractTag(html, tagPattern) {
	const match = html.match(tagPattern);
	return match ? match[1].trim() : null;
}

function readDemos() {
	if (!existsSync(GAME2_DIR)) return [];
	return readdirSync(GAME2_DIR)
		.filter((name) => {
			if (name === 'index.html') return false;
			const full = GAME2_DIR + name;
			return statSync(full).isDirectory() && existsSync(full + '/index.html');
		})
		.sort((a, b) => a.localeCompare(b))
		.map((name) => {
			const html = readFileSync(GAME2_DIR + name + '/index.html', 'utf8');
			const title = extractTag(html, /<title>([^<]*)<\/title>/i) ?? name;
			const description = extractTag(
				html,
				/<meta\s+name=["']description["']\s+content=["']([^"']*)["']/i
			);
			const href = `/game2/${name}/`;
			return { name, title, description, href };
		});
}

function renderRow(demo) {
	const descriptionHtml = demo.description
		? `\n        <p class="desc">${escapeHtml(demo.description)}</p>`
		: '';
	return `      <li>
        <a href="${demo.href}">${escapeHtml(demo.title)}</a>
        <code>${demo.name}</code>${descriptionHtml}
      </li>`;
}

function renderPage(demos) {
	const rows = demos.map(renderRow).join('\n');
	return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="robots" content="noindex, nofollow" />
<link rel="icon" href="/favicon.svg" />
<title>Game2 demos — index</title>
<!-- Generated by scripts/game2-index.mjs — do not hand-edit; gitignored, rebuilt on every dev/build run. -->
<style>
  :root { color-scheme: dark; }
  html, body {
    margin: 0;
    min-height: 100%;
    background: #0e1420;
    color: #e2e8f0;
    font: 15px/1.5 system-ui, -apple-system, "Segoe UI", sans-serif;
  }
  main {
    max-width: 720px;
    margin: 0 auto;
    padding: 48px 20px 80px;
  }
  h1 { color: #f1f5f9; margin-bottom: 4px; }
  .lede { color: #93a3b8; margin-top: 0; }
  .lede a { color: #93c5fd; }
  ul { list-style: none; padding: 0; margin: 32px 0 0; }
  li {
    padding: 16px 0;
    border-top: 1px solid #1e293b;
  }
  li a {
    color: #93c5fd;
    font-size: 17px;
    font-weight: 600;
    text-decoration: none;
  }
  li a:hover { text-decoration: underline; }
  li code {
    margin-left: 10px;
    color: #64748b;
    font-size: 13px;
  }
  .desc {
    margin: 6px 0 0;
    color: #94a3b8;
    font-size: 14px;
  }
  footer {
    margin-top: 48px;
    color: #64748b;
    font-size: 13px;
  }
</style>
</head>
<body>
<main>
  <h1>Game2 demos</h1>
  <p class="lede">
    Every Godot-exported demo under <code>static/game2/</code>, generated
    from each one's own &lt;title&gt;. None of these are linked from the
    real site. See <a href="${DOC_URL}">docs/game2.md</a> for the full
    brief, the inspiration, and the reasoning behind each one.
  </p>
  <ul>
${rows}
  </ul>
  <footer>This page is regenerated automatically — see scripts/game2-index.mjs.</footer>
</main>
</body>
</html>
`;
}

const demos = readDemos();
writeFileSync(OUTPUT_FILE, renderPage(demos));
console.log(`game2-index: wrote ${OUTPUT_FILE} with ${demos.length} demo(s): ${demos.map((d) => d.name).join(', ')}`);
